Fix nginx comilation error
To avoid stopping bosh with the error
<pre>
src/core/ngx_resolver.c: In function ‘ngx_resolver_process_ptr’:
src/core/ngx_resolver.c:1425:43: error: variable ‘qclass’ set but not used [-Werror=unused-but-set-variable]
src/core/ngx_resolver.c:1425:36: error: variable ‘qtype’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
</pre>
on compilation of nginx.

Conflicts:
	src/gorouter/src/code.google.com/p/gogoprotobuf
	src/gorouter/src/github.com/cloudfoundry/go_cfmessagebus
	src/gorouter/src/github.com/cloudfoundry/gorouter
	src/gorouter/src/github.com/cloudfoundry/gosteno
	src/gorouter/src/github.com/cloudfoundry/loggregatorlib
	src/gorouter/src/github.com/cloudfoundry/yagnats
	src/gorouter/src/github.com/nu7hatch/gouuid
	src/gorouter/src/github.com/rcrowley/go-metrics